# Generated by Django 5.2.6 on 2025-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaned_feedback',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='cleaned_feedback',
            name='sentiment',
        ),
        migrations.AlterField(
            model_name='cleaned_feedback',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
