# Generated by Django 5.2.6 on 2025-09-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cleaned_feedback_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaned_feedback',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
