export const serviceNames = [
  "Sustainability in Libraries: Green Practices for Information Institutions",
  "Digital Archiving and Preservation Strategies",
  "Community Outreach Programs for Local Libraries",
  "Library Marketing and Engagement Techniques",
  "Emerging Technologies in Information Management",
  "User Experience Optimization in Public Libraries",
  "Innovative Cataloging Methods for Modern Libraries",
  "E-Resources Access and Licensing Solutions",
  "Library Data Analytics and Reporting",
  "Information Literacy Workshops for Students",
  "Open Access and Scholarly Communication",
  "Special Collections Management and Access",
  "Interlibrary Loan Processes and Automation",
  "Virtual Reference Services and Chat Support",
  "Copyright and Intellectual Property Guidance",
  "Digital Inclusion Initiatives for Underserved Communities",
  "Mobile Library Services and Outreach Vans",
  "Library Space Planning and Renovation Projects",
  "Reader Advisory and Personalized Recommendations",
  "Archives Digitization and Metadata Standards",
  "Inclusive Library Programming for All Ages",
  "Grant Writing and Fundraising for Libraries",
  "Library Policy Development and Implementation",
  "Community Collaboration and Partnership Building",
  "Professional Development Workshops for Librarians",
  "Library Event Planning and Public Engagement",
  "Accessibility Services for Print and Digital Materials",
  "Disaster Recovery and Library Continuity Planning",
  "Library Automation Systems and Software Training",
  "Catalog Cleanup and Data Quality Assurance",
  "User Behavior Tracking and Service Optimization",
  "Digital Preservation of Rare Manuscripts",
  "Outreach Programs Targeting Non-Traditional Users",
  "Technology Training Labs and Workshops",
  "Sustainability Practices in Library Operations",
  "Library Branding and Social Media Strategies",
  "Collection Development and Acquisition Policies",
  "Community Needs Assessment and Surveys",
  "Multilingual Resources and Translation Services",
  "Virtual Exhibits and Online Display Curation",
  "Library Security and Safety Procedures",
  "Artificial Intelligence Applications in Libraries",
  "Information Governance and Compliance",
  "Library Chatbots and Automated Reference Services",
  "Advanced Search and Discovery Tools Implementation",
  "Library Makerspaces and Innovation Labs",
  "Student Success Initiatives and Support Programs",
  "Cultural Heritage Digitization Projects",
  "Historical Manuscript Digitization and Annotation",
  "Integrating Augmented Reality Experiences in Library Spaces",
  // One extra long service name (~200 characters)
  "Comprehensive Strategies for Integrating Sustainable Practices, Cutting-Edge Technology, Community Outreach, and Digital Preservation in Modern Libraries and Information Institutions Globally",
];
