# Generated by Django 5.2.3 on 2025-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('service', models.CharField(choices=[('Hybrid Seminar', 'Hybrid Seminar'), ('Material Requests', 'Material Requests'), ('Online Library', 'Online Library'), ('Library Tour', 'Library Tour')], max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('feedback', models.TextField(max_length=100)),
                ('sentiment', models.TextField(max_length=10)),
            ],
        ),
    ]
