# Generated by Django 5.2.3 on 2025-08-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_archivepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepost',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
