# Generated by Django 5.2.3 on 2025-06-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_sentimentpost_delete_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentpost',
            name='service',
            field=models.CharField(choices=[('Hybrid Seminar', 'Hybrid Seminar'), ('Material Requests', 'Material Requests'), ('Online Library', 'Online Library'), ('Library Tour', 'Library Tour')], max_length=100),
        ),
    ]
