# Generated by Django 5.2.3 on 2025-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0003_archivepost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
