# Generated by Django 5.2.3 on 2025-08-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0005_create_analyst_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentpost',
            name='session',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
