# Generated by Django 5.2.3 on 2026-01-22 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0007_cleaned_feedback_labeled_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaned_feedback',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='labeled_feedback',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf.cleaned_feedback', unique=True),
        ),
    ]
