# Generated by Django 5.2.3 on 2026-01-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0008_alter_cleaned_feedback_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_file', models.FileField(upload_to='sql_dumps/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
