# Generated by Django 5.2.3 on 2026-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0010_filemigration_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemigration',
            name='migrated_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filemigration',
            name='migration_duration',
            field=models.FloatField(default=0.0, help_text='Migration time in seconds'),
        ),
        migrations.AddField(
            model_name='filemigration',
            name='skipped_rows',
            field=models.IntegerField(default=0),
        ),
    ]
