# Generated by Django 5.2.3 on 2026-02-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0011_filemigration_migrated_rows_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemigration',
            options={'verbose_name': 'Upload migration file', 'verbose_name_plural': 'Upload migration files'},
        ),
    ]
