# Generated by Django 5.2.3 on 2026-02-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0013_create_filemigration_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemigration',
            options={'default_permissions': ('add',), 'verbose_name': 'Upload migration file', 'verbose_name_plural': 'Upload migration files'},
        ),
    ]
