# Generated by Django 5.2.3 on 2026-09-07 03:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0015_sentimentcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentcorrection',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 7, 3, 47, 13, 946125, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentimentcorrection',
            name='labeled_feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='drf.labeled_feedback'),
        ),
    ]
