# Generated by Django 5.2.3 on 2026-09-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0016_sentimentcorrection_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50, unique=True)),
                ('model_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('samples_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_on_corrections', models.ManyToManyField(blank=True, to='drf.sentimentcorrection')),
            ],
        ),
    ]
