# Generated by Django 5.2.3 on 2025-08-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
