# Generated by Django 5.2.3 on 2025-08-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
