# Generated by Django 5.2.3 on 2025-08-23 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='"Required. 150 characters or fewer. Letters, digits, spaces and @/./+/-/_ only."', regex='^[\\w.@+\\- ]+\\Z')]),
        ),
    ]
