# Generated by Django 5.2.3 on 2025-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='picture',
            new_name='picture_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
