# Generated by Django 5.2.3 on 2026-08-29 04:12

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_picture_customuser_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='The email must have a valid domain name.', regex=re.compile('^[a-zA-Z0-9_.-]+@stii\\.dost\\.gov\\.ph$', 2))]),
        ),
    ]
